export const VIEW_CLUSTER = "cluster"
export const VIEW_CONSOLE = "console"
export const VIEW_DEMO = "demo"
export const CLUSTER_VIEW_BackendForm = "BackendForm"
export const CLUSTER_VIEW_BackendList = "BackendList"
export const CLUSTER_VIEW_SetBackendTags = "SetBackendTags"

export const DEMO_VIEW_BIGDL = "bigdl"
export const DEMO_VIEW_NLP = "nlp"
export const DEMO_VIEW_STREAM = "stream"