export const VIEW_CLUSTER = "cluster"
export const VIEW_CONSOLE = "console"
export const CLUSTER_VIEW_BackendForm = "BackendForm"
export const CLUSTER_VIEW_BackendList = "BackendList"
export const CLUSTER_VIEW_SetBackendTags = "SetBackendTags"